const Snacks = [
  {
    title: "Pocky Sticks",
    price: 3.5,
    originCountry: "Japan",
    flavor: "Chocolate",
    texture: "Crunchy",
    imageUrl: "",
    altText: "",
  },
  {
    title: "Biscotti",
    price: 4.0,
    originCountry: "Italy",
    flavor: "Almond",
    texture: "Crunchy",
    imageUrl: "",
    altText: "",
  },
  {
    title: "Tortilla Chips",
    price: 2.5,
    originCountry: "Mexico",
    flavor: "Salty",
    texture: "Crunchy",
    imageUrl: "",
    altText: "",
  },
  {
    title: "Baklava",
    price: 5.0,
    originCountry: "Greece",
    flavor: "Honey",
    texture: "Chewy",
    imageUrl: "",
    altText: "",
  },
  {
    title: "Churros",
    price: 3.75,
    originCountry: "Spain",
    flavor: "Cinnamon",
    texture: "Crunchy",
    imageUrl: "",
    altText: "",
  },
  {
    title: "Vegemite on Toast",
    price: 1.5,
    originCountry: "Australia",
    flavor: "Savory",
    texture: "Spread",
    imageUrl: "",
    altText: "",
  },
  {
    title: "Samosas",
    price: 4.5,
    originCountry: "India",
    flavor: "Spicy Potato",
    texture: "Fried",
    imageUrl: "",
    altText: "",
  },
  {
    title: "Jelly Babies",
    price: 2.75,
    originCountry: "UK",
    flavor: "Fruity",
    texture: "Chewy",
    imageUrl: "",
    altText: "",
  },
  {
    title: "Biltong",
    price: 6.0,
    originCountry: "South Africa",
    flavor: "Beef",
    texture: "Dried",
    imageUrl: "",
    altText: "",
  },
  {
    title: "Chili Lime Mango",
    price: 4.0,
    originCountry: "Costa Rica",
    flavor: "Spicy & Sweet",
    texture: "Dried",
    imageUrl: "",
    altText: "",
  },
  {
    title: "Rice Cakes",
    price: 1.99,
    originCountry: "China",
    flavor: "Plain",
    texture: "Crunchy",
    imageUrl: "",
    altText: "",
  },
  {
    title: "Pineapple Tarts",
    price: 5.5,
    originCountry: "Singapore",
    flavor: "Pineapple",
    texture: "Baked",
    imageUrl: "",
    altText: "",
  },
  {
    title: "Nougat",
    price: 3.5,
    originCountry: "France",
    flavor: "Honey Almond",
    texture: "Chewy",
    imageUrl: "",
    altText: "",
  },
  {
    title: "Coconut Candy",
    price: 4.25,
    originCountry: "Philippines",
    flavor: "Coconut",
    texture: "Chewy",
    imageUrl: "",
    altText: "",
  },
  {
    title: "Jamaican Beef Patties",
    price: 4.0,
    originCountry: "Jamaica",
    flavor: "Spicy Beef",
    texture: "Baked",
    imageUrl: "",
    altText: "",
  },
  {
    title: "Curry Chips",
    price: 2.99,
    originCountry: "Thailand",
    flavor: "Curry",
    texture: "Crunchy",
    imageUrl: "",
    altText: "",
  },
  {
    title: "Puffed Rice",
    price: 1.75,
    originCountry: "Bangladesh",
    flavor: "Plain",
    texture: "Crunchy",
    imageUrl: "",
    altText: "",
  },
  {
    title: "Baba Ghanoush with Pita",
    price: 3.5,
    originCountry: "Lebanon",
    flavor: "Eggplant",
    texture: "Dip",
    imageUrl: "",
    altText: "",
  },
  {
    title: "Dulce de Leche Cookies",
    price: 3.0,
    originCountry: "Argentina",
    flavor: "Caramel",
    texture: "Chewy",
    imageUrl: "",
    altText: "",
  },
];
